# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['vikingzero', 'vikingzero.agents', 'vikingzero.environments']

package_data = \
{'': ['*']}

install_requires = \
['PyYAML>=5.3.1,<6.0.0',
 'gym>=0.17.2,<0.18.0',
 'h5py>=2.10.0,<3.0.0',
 'jupyter>=1.0.0,<2.0.0',
 'jupyterlab>=2.2.2,<3.0.0',
 'matplotlib>=3.3.0,<4.0.0',
 'numpy==1.16.4',
 'pymongo>=3.11.0,<4.0.0',
 'python-dotenv>=0.14.0,<0.15.0',
 'tables>=3.6.1,<4.0.0',
 'tensorboard>=2.3.0,<3.0.0',
 'tensorboardX>=2.1,<3.0',
 'tensorflow>=2.3.1,<3.0.0',
 'torch>=1.6.0,<2.0.0',
 'torchvision>=0.7.0,<0.8.0',
 'tqdm>=4.50.2,<5.0.0']

setup_kwargs = {
    'name': 'vikingzero',
    'version': '0.1.1',
    'description': '',
    'long_description': None,
    'author': 'David SeWell',
    'author_email': 'davidsewell3145@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
